cargo-features = ["profile-rustflags"]

[workspace]
members = ["core", "frontend", "cli", "renderer", "db", "macros"]
default-members = ["frontend"]
resolver = "3"

[workspace.package]
version = "0.2.10"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/EmIsGreat/Monsoon-Emulator"
keywords = ["nes", "emulator", "nintendo"]
categories = ["emulators", "game-development"]

[workspace.dependencies]
monsoon-core = { version = "0.2.10", path = "core" }
monsoon-default-renderers = { version = "0.2.10", path = "renderer" }
monsoon-db = { version = "0.2.10", path = "db" }
monsoon-macro = { version = "0.2.10", path = "macros" }

[profile.release]
lto = "fat"
codegen-units = 1

[profile.native]
inherits = "release"
rustflags = ["-C", "target-cpu=native"]

[profile.dev]
opt-level = 3
split-debuginfo = "unpacked"  # Ensures symbols are separate

[profile.profiling]
inherits = "release"
split-debuginfo = "unpacked"  # Ensures symbols are separate
strip = "none"
debug = true
panic = 'unwind'
